In [1]:
import numpy as np
import random

In [2]:
np.random.seed(123)

In [3]:
sample = np.random.normal(100,1,3)
sample

array([ 98.9143694 , 100.99734545, 100.2829785 ])

In [4]:
population = np.arange(1,101)
population

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
np.random.choice(population,size=10)

array([84, 58, 87, 98, 97, 48, 74, 33, 47, 97])